source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TCSBLL_Example', :exclusive => true do
  pod "TCSBLL", :path => "../"
end

target 'TCSBLL_Tests', :exclusive => true do
  pod "TCSBLL", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
