#source 'https://github.com/spbreak/spbreakSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'TCSBLL_Example', :exclusive => true do
  pod "TCSBLL", :path => "../"
#  pod 'TCSDAL', '~>0.7.0'
end

target 'TCSBLL_Tests', :exclusive => true do
  pod "TCSBLL", :path => "../"

  pod 'Kiwi'
end
